<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250318192417 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Création du type ENUM pour les priorités de tâches et de la table task';
    }

    public function up(Schema $schema): void
    {
        // Créer d'abord le type ENUM natif PostgreSQL
        $this->addSql("CREATE TYPE task_priority_enum AS ENUM ('basse', 'normale', 'haute', 'critique')");

        // Ensuite créer la table qui utilise ce type
        $this->addSql('CREATE TABLE task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, priority task_priority_enum NOT NULL, PRIMARY KEY(id))');
    }

    public function down(Schema $schema): void
    {
        // Supprimer d'abord la table
        $this->addSql('DROP TABLE task');

        // Puis supprimer le type ENUM
        $this->addSql('DROP TYPE task_priority_enum');
    }
}
