<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use App\Doctrine\Type\TaskPriorityEnumType;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250319040536 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Task / TaskPriorityEnumType';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(TaskPriorityEnumType::getCreateTypeSQL());

        $this->addSql('CREATE TABLE task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, priority task_priority_enum NOT NULL, PRIMARY KEY(id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE task');

        $this->addSql(TaskPriorityEnumType::getDropTypeSQL());
    }
}
